using System;
using System.Collections.Generic;
using System.Text;

namespace Hangman
{
    public class Countries
    {
        public static string GetRandom()
        {
            var rand = new Random();
            int index = rand.Next(CountryList.Length);
            return CountryList[index];
        }

        public static string[] CountryList = {
            "Albania",
            "Andorra",
            "Armenia",
            "Austria",
            "Azerbaijan",
            "Belarus",
            "Belgium",
            "Bulgaria",
            "Croatia",
            "Cyprus",
            "Czech",
            "Republic",
            "Denmark",
            "Estonia",
            "Finland",
            "France",
            "Georgia",
            "Germany",
            "Greece",
            "Hungary",
            "Iceland",
            "Ireland",
            "Italy",
            "Kazakhstan",
            "Latvia",
            "Lithuania",
            "Luxembourg",
            "Malta",
            "Moldova",
            "Montenegro",
            "Netherlands",
            "Norway",
            "Poland",
            "Portugal",
            "Romania",
            "Russia",
            "San Marino",
            "Serbia",
            "Slovakia",
            "Slovenia",
            "Spain",
            "Sweden",
            "Switzerland",
            "Turkey",
            "Ukraine",
            "United Kingdom",
            "Algeria",
            "Egypt",
            "Libya",
            "Morocco",
            "Tunisia",
            "Burundi",
            "Comoros",
            "Eritrea",
            "Ethiopia",
            "Kenya",
            "Madagascar",
            "Malawi",
            "Mauritius",
            "Mayotte",
            "Mozambique",
            "Rwanda",
            "Somalia",
            "Somaliland",
            "Sudan",
            "Tanzania",
            "Uganda",
            "Angola",
            "Cameroon",
            "Chad",
            "Botswana",
            "Namibia",
            "Zambia",
            "Zimbabwe",
            "South Africa",
            "Benin",
            "Cape Verde",
            "Gambia",
            "Ghana",
            "Guinea",
            "Liberia",
            "Niger",
            "Nigeria",
            "Saint Helena",
            "Senegal",
            "Sierra Leone",
            "United States",
            "Antigua",
            "Argentina",
            "Bolivia",
            "Brazil",
            "Canada",
            "Chile",
            "Colombia",
            "Costa Rica",
            "Cuba",
            "Ecuador",
            "El Salvador",
            "French Guiana",
            "Guyana",
            "Haiti",
            "Honduras",
            "Jamaica",
            "Mexico",
            "Nicaragua",
            "Panama",
            "Paraguay",
            "Peru",
            "Puerto Rico",
            "Uruguay",
            "Venezuela",
            "Afghanistan",
            "Armenia",
            "Azerbaijan",
            "Bahrain",
            "Bangladesh",
            "China",
            "Cyprus",
            "Georgia",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Israel",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kuwait",
            "Laos",
            "Lebanon",
            "Malaysia",
            "Maldives",
            "Mongolia",
            "Myanmar",
            "Nepal",
            "North Korea",
            "Oman",
            "Pakistan",
            "Palestine",
            "Philippines",
            "Qatar",
            "Russia",
            "Saudi Arabia",
            "Singapore",
            "South",
            "Korea",
            "Sri Lanka",
            "Syria",
            "Taiwan",
            "Tajikistan",
            "Thailand",
            "Turkey",
            "Turkmenistan",
            "United Arab Emirates",
            "Uzbekistan",
            "Vietnam",
            "Yemen",
            "Australia",
            "Tasmania",
            "New Zealand",
            "New Guinea" };
    }
}

